### PR TITLE
Update author config

### PR DESCRIPTION
**Pull request by monmanuela**

### CODE REVIEW

**Comment by yong24s** [comment]
@monmanuela 

According to [Netlify](https://deploy-preview-6--ecstatic-goldwasser-4c5dd4.netlify.com/), you have unaccounted commits. 

Your git author name should be `Monika Manuela Hengki`.

```
git shortlog -e -s | grep m***@gmail.com
     3  Monika Manuela Hengki <m***@gmail.com>
```

**Comment by monmanuela** [comment]
@yong24s I thought the git author name follows this one?
image

If I'm not wrong I also put this name for my 2103T reposense, though I'm not sure now maybe I have some unaccounted commits too back then 🤔

**Comment by yong24s** [comment]
🤔

Your pull-requests to TEAMMATES are committed through GitHub, so GitHub actually use your GitHub name instead of your local git. 😮

**Comment by monmanuela** [comment]
@yong24s 😱 
Fixed, thanks for letting me know!

**Comment by damithc** [comment]
@yong24s For some reason, netlify preview for this PR doesn't seem to be loading.

**Comment by yong24s** [comment]
Works for me tho 🤔

**Pull request merged**
