### PR TITLE
Update author-config.csv

### PR DESCRIPTION
**Pull request by ongspxm**
updated author config

### CODE REVIEW

**Comment by yong24s** [comment]
@ongspxm 

Can do a force push to trigger rebuild.

**Comment by ongspxm** [comment]
@yong24s Cannot dah :cry: 
```
fatal: destination path 'RepoSense' already exists and is not an empty directory.
```

**Comment by yong24s** [comment]
😆 Remake a new PR.

**Comment by ongspxm** [comment]
Haiz

**Pull request closed without merging**
